### ISSUE TITLE
Expose Generic* stuff to JavaScript

### ISSUE THREAD

**Issue by targos** [cheminfo/openchemlib-js#136]
Project: https://github.com/orgs/cheminfo/projects/11/views/1

<details>

<summary>Old tasklist</summary>

```[tasklist]
### Tasks
- [ ] check if molecule needs to be cloned (do not change input)
- [ ] Improve custom cursors (they are too big)
- [x] Double click to open query feature (fragment mode, lasso) (tpoisseau)
- [ ] Implement drawRectangle (find how it can be called)
- [ ] Change highlight colour to blue (in general, make sure colors are same as java version) (tpoisseau)
- [x] Dialog: OK on the right (tpoisseau)
- [x] bug: scroll on focus (not in Firefox) -> preventScroll (tpoisseau)
- [x] redraw on submit form/dialog (internally, updateAndFireEvent(UPDATE_REDRAW) is normally called) (tpoisseau)
- [ ] Read-only mode. Main goal is to display reactions because there is no getSVG method for them
- [ ] how to unregister editor and event listeners (memory leak) -> maybe editor.destroy()
- [ ] Create custom elements / shadow root (dialogs and main element). Example with current editor: https://github.com/artaius/openchemlib-vaadin
- [ ] Playwright tests
- [ ] Implement popup menu
- [ ] Center dialogs on editor root element
- [ ] Include documentation as self-contained HTML
- [ ] onChange with tests
- [ ] Allow some level of customization for dialogs?
- [ ] Copy RXN to clipboard
- [ ] Possibly decoupled toolbar
- [ ] Implement dark mode
- [x] Fix bug with toolbar button highlighting
- [x] Implement dialogs
```

</details>

**Comment by targos** [comment]
To do after https://github.com/cheminfo/openchemlib-js/pull/135
